from src.configs.secret import DATA_SOURCE_END_POINT, DATA_SOURCE_AUTHORIZATION, DATA_SOURCE_SERVICE_KEY

END_POINT = DATA_SOURCE_END_POINT
AUTHORIZATION = DATA_SOURCE_AUTHORIZATION
SERVICE_KEY = DATA_SOURCE_SERVICE_KEY

BATCH_SIZE = 10
